using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UtopiaCity.Models.TimelineModel
{
    public class TimelineModel
    {

        //value of the property will be generated by the database on the INSERT statement. This Identity property cannot be updated.
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string ID { get; set; }

        //CHANGE MODEL FOR SHOW ONLY DAY AND YEAR
        [DataType(DataType.Date)]
        [Display(Name = "День и год")]
        public DateTime DayAndYear { get; set; }

        [Display(Name = "Расписание")]
        public string Schedule { get; set; }

        //public bool TranscriptionOfPermission { get; set; }
        [Display(Name = "Транскрипция разрешений")]
        public string TranscriptionOfPermission { get; set; }

        [Display(Name = "Уникальные правила")]
        public string UniqueRules { get; set; }
    }
}
